name: Week_12
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
    restart: unless-stopped
    environment:
      - discovery.type="single-node"
      - xpack.security.enabled="false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    networks:
      - es-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ES_HOST=http://elasticsearch:9200
      - INDEX_NAME=tweets
    depends_on:
      elasticsearch: { condition: service_healthy }
    ports:
      - "8000:8000"
    networks:
      - es-net
    restart: unless-stopped

networks:
  es-net:
    name: es-net